More KK_Pregnancy config options
ManlyMarco/KoikatuGameplayMods pull request #7
Opened 2020-10-16 05:07 UTC by thojmr

Added two new config options for KK_Pregnancy

- ConceptionOverrideEnabled: flag to allow enabling conception globally for all characters.  (So you don't have to manually enable for each and every character card)

- InflationSpeed: for 1x, 2x, 3x belly inflation speeds.

If you want me to change anything let me know,
Thanks

2020-10-20 11:02 UTC, ManlyMarco requested changes
Thanks for the PR!

The pregnancy being disabled by default was a bug introduced in a recent version. I fixed it thanks to someone giving me good info to work off of https://github.com/ManlyMarco/KoikatuGameplayMods/commit/6fa9107a37636d3516a5ec97ea993294a918b7b5
This makes the ConceptionOverrideEnabled redundant since now pregnancy is always on by default, so the setting should be removed.

The inflation setting is a good idea, I'll merge it when you remove the override setting.

2020-10-21 01:42 UTC, thojmr commented
Sure thing.  I'll make the changes and let you know.  Bear with my while I fumble around with this pull request :)

2020-10-21 02:32 UTC, thojmr commented
Alright my changes are complete.  

- ConceptionOverride was removed

- FertilityOverride was added.  Allows you to set a default global fertility level from 30%-100%

If I missed anything let me know!

2020-10-21 14:51 UTC, ManlyMarco commented on KK_Pregnancy/PregnancyGameController.cs
> +                var fertility = (PregnancyPlugin.FertilityOverride.Value > controller.Data.Fertility) ? PregnancyPlugin.FertilityOverride.Value : controller.Data.Fertility;
This will not allow characters to ever have less than 0.3 fertility since the setting's lowest value is 0.3 and it can't be disabled.

2020-10-21 14:55 UTC, ManlyMarco approved these changes

2020-10-21 15:02 UTC, ManlyMarco commented on KK_Pregnancy/PregnancyGameController.cs
> +                var fertility = (PregnancyPlugin.FertilityOverride.Value > controller.Data.Fertility) ? PregnancyPlugin.FertilityOverride.Value : controller.Data.Fertility;
The setting description makes it sound like the value will be forced to the exact value the setting gives you, so maybe change the wording of the setting and add a 0 option; or change the setting to use an enum that has an "Off" option alongside"OverrideTo50" etc, then have a switch here that hard sets the fertility value.

2020-10-21 18:48 UTC, thojmr commented
Good points.  I've updated the descriptions, and added a value of 0f as the default selected value.

Thanks!

2020-10-22 01:33 UTC, merged

2020-10-22 01:34 UTC, ManlyMarco commented
Looks good, thank you for the PR!